name: "Django Setup Action"
description: "Custom action for setting up django projects"
author: "Mokhlesur Mahin"

inputs:
  python:
    description: "python version"
    required: true
    default: "3.9"

  django:
    description: "django version"
    required: true
    default: "3.2"


runs:
  using: "docker"
  image: "Dockerfile"

branding:
  icon: "package"


args:
- ${{ inputs.python }}
- $ {{ inputs.django }}
